// Template for the renderer's Supabase config.
//
// The real file (packages/desktop/supabase-config.js) is GIT-IGNORED and
// generated by scripts/sync-supabase.js from the environment
// (EXPO_PUBLIC_SUPABASE_URL / EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY) or from
// packages/mobile/.env — mirroring the mobile app, which keeps the same values
// in its own git-ignored .env. You normally do NOT create it by hand: set up
// packages/mobile/.env (see packages/mobile/.env.example) and `npm start`
// regenerates supabase-config.js for you. Copy this file to supabase-config.js
// only if you want to hardcode the values instead.
window.LECTIO_SUPABASE = {
  url: 'https://YOUR-PROJECT.supabase.co',
  anonKey: 'sb_publishable_xxx',
};
