'use strict';
// Supabase client for the Electron renderer.
//
// supabase-js is browser code, so the client lives here in the renderer (not the
// main process). The renderer runs with contextIsolation:true /
// nodeIntegration:false but still has localStorage, so supabase-js's default
// browser session persistence works and sessions survive relaunches. fs-storage
// stays in main as the data store — this file only adds an authenticated
// session; it does NOT switch storage (that's prompt 11.2).
//
// Loaded AFTER two scripts in index.html (order matters):
//   - supabase.js        → window.supabase       (the UMD bundle; has createClient)
//   - supabase-config.js → window.LECTIO_SUPABASE = { url, anonKey }
// Both are vendored/generated by scripts/sync-supabase.js and git-ignored.
//
// Exposes window.lectioSupabase for auth.js and the future storage adapter. On a
// missing bundle or config it exposes null (instead of throwing) so the renderer
// still loads — auth.js then degrades to a clear "cannot reach the server" path.
(function () {
  const cfg = window.LECTIO_SUPABASE || {};
  const createClient = window.supabase && window.supabase.createClient;

  if (typeof createClient !== 'function') {
    console.error('[supabase-client] supabase-js UMD bundle not loaded.');
    window.lectioSupabase = null;
    return;
  }
  if (!cfg.url || !cfg.anonKey) {
    console.error(
      '[supabase-client] Missing Supabase config. Set packages/mobile/.env ' +
        '(or EXPO_PUBLIC_SUPABASE_* env vars) and restart.'
    );
    window.lectioSupabase = null;
    return;
  }

  window.lectioSupabase = createClient(cfg.url, cfg.anonKey, {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false,
    },
  });
})();
